//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Журнал заказов.
    /// </summary>
    // *** Start programmer edit section *** (ЖурналЗаказов CustomAttributes)

    // *** End programmer edit section *** (ЖурналЗаказов CustomAttributes)
    [AutoAltered()]
    [Caption("Журнал заказов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖурналЗаказовE", new string[] {
            "Дата as \'Дата\'",
            "Заказ as \'Номер заказа\'",
            "Заказ.НомерЗаказа as \'Номер заказа\'",
            "Заказ.Мастер.ФИО as \'Мастер\'",
            "СтатусЗаказа as \'Статус заказа\'"}, Hidden=new string[] {
            "Заказ.НомерЗаказа"})]
    [MasterViewDefineAttribute("ЖурналЗаказовE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗаказа")]
    [View("ЖурналЗаказовL", new string[] {
            "Дата as \'Дата\'",
            "Заказ.НомерЗаказа as \'Номер заказа\'",
            "Заказ.Мастер.ФИО as \'Мастер\'",
            "СтатусЗаказа as \'Статус заказа\'"})]
    public class ЖурналЗаказов : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Probatri.Статус fСтатусЗаказа;
        
        private IIS.Probatri.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (ЖурналЗаказов CustomMembers)

        // *** End programmer edit section *** (ЖурналЗаказов CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналЗаказов.Дата CustomAttributes)

        // *** End programmer edit section *** (ЖурналЗаказов.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.Дата Get start)

                // *** End programmer edit section *** (ЖурналЗаказов.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЖурналЗаказов.Дата Get end)

                // *** End programmer edit section *** (ЖурналЗаказов.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.Дата Set start)

                // *** End programmer edit section *** (ЖурналЗаказов.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЖурналЗаказов.Дата Set end)

                // *** End programmer edit section *** (ЖурналЗаказов.Дата Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналЗаказов.СтатусЗаказа CustomAttributes)

        // *** End programmer edit section *** (ЖурналЗаказов.СтатусЗаказа CustomAttributes)
        public virtual IIS.Probatri.Статус СтатусЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Get start)

                // *** End programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Get start)
                IIS.Probatri.Статус result = this.fСтатусЗаказа;
                // *** Start programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Get end)

                // *** End programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Set start)

                // *** End programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Set start)
                this.fСтатусЗаказа = value;
                // *** Start programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Set end)

                // *** End programmer edit section *** (ЖурналЗаказов.СтатусЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Журнал заказов.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналЗаказов.Заказ CustomAttributes)

        // *** End programmer edit section *** (ЖурналЗаказов.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Probatri.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.Заказ Get start)

                // *** End programmer edit section *** (ЖурналЗаказов.Заказ Get start)
                IIS.Probatri.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (ЖурналЗаказов.Заказ Get end)

                // *** End programmer edit section *** (ЖурналЗаказов.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналЗаказов.Заказ Set start)

                // *** End programmer edit section *** (ЖурналЗаказов.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (ЖурналЗаказов.Заказ Set end)

                // *** End programmer edit section *** (ЖурналЗаказов.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖурналЗаказовE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналЗаказовE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналЗаказовE", typeof(IIS.Probatri.ЖурналЗаказов));
                }
            }
            
            /// <summary>
            /// "ЖурналЗаказовL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналЗаказовL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналЗаказовL", typeof(IIS.Probatri.ЖурналЗаказов));
                }
            }
        }
    }
}
