//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "Дата as \'Дата\'",
            "НомерЗаказа as \'Номер заказа\'",
            "Мастер as \'Мастер\'",
            "Мастер.ФИО as \'Мастер\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.Контрагент as \'Контрагент\'",
            "Итог as \'Итог\'"}, Hidden=new string[] {
            "Мастер.ФИО",
            "Контрагент.Контрагент"})]
    [AssociatedDetailViewAttribute("ЗаказE", "РасчетЗаказа", "РасчетЗаказаE", true, "", "Расчет заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "Мастер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ЗаказE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("ЗаказL", new string[] {
            "Дата as \'Дата\'",
            "НомерЗаказа as \'Номер заказа\'",
            "Мастер.ФИО as \'Мастер\'",
            "Контрагент.Контрагент as \'Контрагент\'",
            "Итог as \'Итог\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерЗаказа;
        
        private double fИтог;
        
        private IIS.Probatri.Мастер fМастер;
        
        private IIS.Probatri.Контрагент fКонтрагент;
        
        private IIS.Probatri.DetailArrayOfРасчетЗаказа fРасчетЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Итог.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Итог CustomAttributes)

        // *** End programmer edit section *** (Заказ.Итог CustomAttributes)
        public virtual double Итог
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Итог Get start)

                // *** End programmer edit section *** (Заказ.Итог Get start)
                double result = this.fИтог;
                // *** Start programmer edit section *** (Заказ.Итог Get end)

                // *** End programmer edit section *** (Заказ.Итог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Итог Set start)

                // *** End programmer edit section *** (Заказ.Итог Set start)
                this.fИтог = value;
                // *** Start programmer edit section *** (Заказ.Итог Set end)

                // *** End programmer edit section *** (Заказ.Итог Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.Probatri.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Get start)

                // *** End programmer edit section *** (Заказ.Контрагент Get start)
                IIS.Probatri.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (Заказ.Контрагент Get end)

                // *** End programmer edit section *** (Заказ.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Set start)

                // *** End programmer edit section *** (Заказ.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Заказ.Контрагент Set end)

                // *** End programmer edit section *** (Заказ.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Мастер CustomAttributes)

        // *** End programmer edit section *** (Заказ.Мастер CustomAttributes)
        [PropertyStorage(new string[] {
                "Мастер"})]
        [NotNull()]
        public virtual IIS.Probatri.Мастер Мастер
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Мастер Get start)

                // *** End programmer edit section *** (Заказ.Мастер Get start)
                IIS.Probatri.Мастер result = this.fМастер;
                // *** Start programmer edit section *** (Заказ.Мастер Get end)

                // *** End programmer edit section *** (Заказ.Мастер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Мастер Set start)

                // *** End programmer edit section *** (Заказ.Мастер Set start)
                this.fМастер = value;
                // *** Start programmer edit section *** (Заказ.Мастер Set end)

                // *** End programmer edit section *** (Заказ.Мастер Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.РасчетЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.РасчетЗаказа CustomAttributes)
        public virtual IIS.Probatri.DetailArrayOfРасчетЗаказа РасчетЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.РасчетЗаказа Get start)

                // *** End programmer edit section *** (Заказ.РасчетЗаказа Get start)
                if ((this.fРасчетЗаказа == null))
                {
                    this.fРасчетЗаказа = new IIS.Probatri.DetailArrayOfРасчетЗаказа(this);
                }
                IIS.Probatri.DetailArrayOfРасчетЗаказа result = this.fРасчетЗаказа;
                // *** Start programmer edit section *** (Заказ.РасчетЗаказа Get end)

                // *** End programmer edit section *** (Заказ.РасчетЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.РасчетЗаказа Set start)

                // *** End programmer edit section *** (Заказ.РасчетЗаказа Set start)
                this.fРасчетЗаказа = value;
                // *** Start programmer edit section *** (Заказ.РасчетЗаказа Set end)

                // *** End programmer edit section *** (Заказ.РасчетЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Probatri.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Probatri.Заказ));
                }
            }
        }
    }
}
