//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Лица.
    /// </summary>
    // *** Start programmer edit section *** (Лица CustomAttributes)

    // *** End programmer edit section *** (Лица CustomAttributes)
    public enum Лица
    {
        
        // *** Start programmer edit section *** (Лица.Физическое CustomAttributes)

        // *** End programmer edit section *** (Лица.Физическое CustomAttributes)
        [Caption("Физическое")]
        Физическое,
        
        // *** Start programmer edit section *** (Лица.Юридическое CustomAttributes)

        // *** End programmer edit section *** (Лица.Юридическое CustomAttributes)
        [Caption("Юридическое")]
        Юридическое,
    }
}
