//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер.
    /// </summary>
    // *** Start programmer edit section *** (Мастер CustomAttributes)

    // *** End programmer edit section *** (Мастер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МастерE", new string[] {
            "КодМастера as \'Код мастера\'",
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    [View("МастерL", new string[] {
            "КодМастера as \'Код мастера\'",
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    public class Мастер : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМастера;
        
        private string fФИО;
        
        private string fАдрес;
        
        private string fТелефон;
        
        private string fПочта;
        
        // *** Start programmer edit section *** (Мастер CustomMembers)

        // *** End programmer edit section *** (Мастер CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.Адрес CustomAttributes)

        // *** End programmer edit section *** (Мастер.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.Адрес Get start)

                // *** End programmer edit section *** (Мастер.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Мастер.Адрес Get end)

                // *** End programmer edit section *** (Мастер.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.Адрес Set start)

                // *** End programmer edit section *** (Мастер.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Мастер.Адрес Set end)

                // *** End programmer edit section *** (Мастер.Адрес Set end)
            }
        }
        
        /// <summary>
        /// КодМастера.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.КодМастера CustomAttributes)

        // *** End programmer edit section *** (Мастер.КодМастера CustomAttributes)
        public virtual int КодМастера
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.КодМастера Get start)

                // *** End programmer edit section *** (Мастер.КодМастера Get start)
                int result = this.fКодМастера;
                // *** Start programmer edit section *** (Мастер.КодМастера Get end)

                // *** End programmer edit section *** (Мастер.КодМастера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.КодМастера Set start)

                // *** End programmer edit section *** (Мастер.КодМастера Set start)
                this.fКодМастера = value;
                // *** Start programmer edit section *** (Мастер.КодМастера Set end)

                // *** End programmer edit section *** (Мастер.КодМастера Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.Почта CustomAttributes)

        // *** End programmer edit section *** (Мастер.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.Почта Get start)

                // *** End programmer edit section *** (Мастер.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Мастер.Почта Get end)

                // *** End programmer edit section *** (Мастер.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.Почта Set start)

                // *** End programmer edit section *** (Мастер.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Мастер.Почта Set end)

                // *** End programmer edit section *** (Мастер.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.Телефон CustomAttributes)

        // *** End programmer edit section *** (Мастер.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.Телефон Get start)

                // *** End programmer edit section *** (Мастер.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Мастер.Телефон Get end)

                // *** End programmer edit section *** (Мастер.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.Телефон Set start)

                // *** End programmer edit section *** (Мастер.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Мастер.Телефон Set end)

                // *** End programmer edit section *** (Мастер.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.ФИО CustomAttributes)

        // *** End programmer edit section *** (Мастер.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.ФИО Get start)

                // *** End programmer edit section *** (Мастер.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Мастер.ФИО Get end)

                // *** End programmer edit section *** (Мастер.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.ФИО Set start)

                // *** End programmer edit section *** (Мастер.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Мастер.ФИО Set end)

                // *** End programmer edit section *** (Мастер.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МастерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерE", typeof(IIS.Probatri.Мастер));
                }
            }
            
            /// <summary>
            /// "МастерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерL", typeof(IIS.Probatri.Мастер));
                }
            }
        }
    }
}
