//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "НомерТовара as \'Номер товара\'",
            "Товар as \'Товар\'",
            "Цена as \'Цена\'"})]
    [View("НоменклатураL", new string[] {
            "НомерТовара as \'Номер товара\'",
            "Товар as \'Товар\'",
            "Цена as \'Цена\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерТовара;
        
        private string fТовар;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// НомерТовара.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.НомерТовара CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.НомерТовара CustomAttributes)
        public virtual int НомерТовара
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.НомерТовара Get start)

                // *** End programmer edit section *** (Номенклатура.НомерТовара Get start)
                int result = this.fНомерТовара;
                // *** Start programmer edit section *** (Номенклатура.НомерТовара Get end)

                // *** End programmer edit section *** (Номенклатура.НомерТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.НомерТовара Set start)

                // *** End programmer edit section *** (Номенклатура.НомерТовара Set start)
                this.fНомерТовара = value;
                // *** Start programmer edit section *** (Номенклатура.НомерТовара Set end)

                // *** End programmer edit section *** (Номенклатура.НомерТовара Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Товар CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Товар CustomAttributes)
        [StrLen(255)]
        public virtual string Товар
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Товар Get start)

                // *** End programmer edit section *** (Номенклатура.Товар Get start)
                string result = this.fТовар;
                // *** Start programmer edit section *** (Номенклатура.Товар Get end)

                // *** End programmer edit section *** (Номенклатура.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Товар Set start)

                // *** End programmer edit section *** (Номенклатура.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Номенклатура.Товар Set end)

                // *** End programmer edit section *** (Номенклатура.Товар Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Цена CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Цена Get start)

                // *** End programmer edit section *** (Номенклатура.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Номенклатура.Цена Get end)

                // *** End programmer edit section *** (Номенклатура.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Цена Set start)

                // *** End programmer edit section *** (Номенклатура.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Номенклатура.Цена Set end)

                // *** End programmer edit section *** (Номенклатура.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Probatri.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Probatri.Номенклатура));
                }
            }
        }
    }
}
